apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: sit722
spec:
  replicas: 1
  selector:
    matchLabels: { app: order-svc }
  template:
    metadata:
      labels: { app: order-svc }
    spec:
      containers:
      - name: order-service
        image: sit722prodacr.azurecr.io/order-service:latest
        imagePullPolicy: IfNotPresent
        ports: [{ containerPort: 8000 }]
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: sit722
spec:
  type: LoadBalancer
  selector: { app: order-svc }
  ports:
    - port: 8001
      targetPort: 8000